// packages/vue/src/components/blocks/ArcArrow.vue
<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted } from "vue";
import { Color } from "@infinitecanvas/core";
import { Arc, type ArcComputed, type Vec2 } from "@infinitecanvas/math";
import { ArcArrow } from "@infinitecanvas/plugin-arrows";

import { useComponent } from "../../composables/useComponent";
import ArrowHead from "./ArrowHead.vue";
import type { BlockData } from "../../types";
import { getArrowHead } from "../../arrowHeads";

const props = defineProps<BlockData>();

const containerRef = ref<HTMLElement | null>(null);
const clientWidth = ref(0);
const clientHeight = ref(0);

const color = useComponent(props.entityId, Color);
const arcArrow = useComponent(props.entityId, ArcArrow);

// Watch for resize
let resizeObserver: ResizeObserver | null = null;
onMounted(() => {
  if (containerRef.value) {
    resizeObserver = new ResizeObserver(() => {
      if (containerRef.value) {
        clientWidth.value = containerRef.value.clientWidth;
        clientHeight.value = containerRef.value.clientHeight;
      }
    });
    resizeObserver.observe(containerRef.value);
    clientWidth.value = containerRef.value.clientWidth;
    clientHeight.value = containerRef.value.clientHeight;
  }
});

onUnmounted(() => {
  resizeObserver?.disconnect();
});

const hex = computed(() => {
  if (!color.value) return "#000000";
  const r = color.value.red.toString(16).padStart(2, "0");
  const g = color.value.green.toString(16).padStart(2, "0");
  const b = color.value.blue.toString(16).padStart(2, "0");
  return `#${r}${g}${b}`;
});

const baseThickness = computed(() => arcArrow.value?.value[6] ?? 2);
const thickness = computed(() => `${baseThickness.value}px`);

const isEmphasized = computed(() => props.hovered || props.selected);

// Check if the arc is curved (points are not collinear)
const isCurved = computed(() => {
  if (!arcArrow.value) return false;
  const v = arcArrow.value.value;
  // Create arc tuple from UV coords
  const arc = Arc.create(v[0], v[1], v[2], v[3], v[4], v[5], v[6]);
  return !Arc.isCollinear(arc);
});

// Compute world-space arc from UV coordinates
const worldArc = computed(() => {
  if (!arcArrow.value) return null;
  const v = arcArrow.value.value;
  const w = clientWidth.value;
  const h = clientHeight.value;
  return Arc.create(
    v[0] * w,
    v[1] * h,
    v[2] * w,
    v[3] * h,
    v[4] * w,
    v[5] * h,
    v[6],
  );
});

// Compute arc properties (center, radius, etc.)
const arcComputed = computed((): ArcComputed | null => {
  if (!worldArc.value || !isCurved.value) return null;
  return Arc.compute(worldArc.value);
});

// Compute trimmed path data
const pathData = computed(() => {
  if (!arcArrow.value || !worldArc.value) return null;

  const arc = worldArc.value;
  const startHead = arcArrow.value.startArrowHead;
  const endHead = arcArrow.value.endArrowHead;

  const arcLength = Arc.length(arc);

  let tStart = arcArrow.value.trimStart;
  // Add gap if connected to a block and has arrow head
  if (props.connector?.startBlock && startHead !== "none") {
    const headGap = getArrowHead(startHead)?.gap ?? 0;
    const gap = arcLength > 0 ? headGap / arcLength : 0;
    tStart += gap;
  }

  let tEnd = arcArrow.value.trimEnd;
  // Add gap if connected to a block and has arrow head
  if (props.connector?.endBlock && endHead !== "none") {
    const headGap = getArrowHead(endHead)?.gap ?? 0;
    const gap = arcLength > 0 ? headGap / arcLength : 0;
    tEnd += gap; // Add because we use (1 - tEnd) below
  }

  // tEnd is measured from end toward start, so invert it for arc parametric
  const actualTEnd = 1 - tEnd;

  const start = Arc.parametricToPoint(arc, tStart);
  const end = Arc.parametricToPoint(arc, actualTEnd);
  const startDir = flipDirection(Arc.directionAt(arc, tStart));
  const endDir = Arc.directionAt(arc, actualTEnd);

  return {
    start,
    end,
    startDir,
    endDir,
    tStart,
    tEnd: actualTEnd,
    startHead,
    endHead,
  };
});

// SVG path for curved arc
const curvedPath = computed(() => {
  if (!pathData.value || !arcComputed.value || !isCurved.value) return "";

  const { start, end, tStart, tEnd } = pathData.value;
  const { radius, clockwise, arcAngle } = arcComputed.value;

  const trimmedArcAngle = arcAngle * (tEnd - tStart);
  const largeArc = trimmedArcAngle > Math.PI ? 1 : 0;
  const sweep = clockwise ? 0 : 1;

  return `M ${start[0]} ${start[1]} A ${radius} ${radius} 0 ${largeArc} ${sweep} ${end[0]} ${end[1]}`;
});

// SVG line for straight arrow
const straightLinePoints = computed(() => {
  if (!pathData.value || isCurved.value) return null;
  return {
    x1: pathData.value.start[0],
    y1: pathData.value.start[1],
    x2: pathData.value.end[0],
    y2: pathData.value.end[1],
  };
});

function flipDirection(dir: Vec2): Vec2 {
  return [-dir[0], -dir[1]];
}
</script>

<template>
  <div ref="containerRef" class="ic-arc-arrow">
    <svg class="arrow-svg" preserveAspectRatio="none">
      <!-- Curved arc path -->
      <template v-if="isCurved && curvedPath">
        <path
          :d="curvedPath"
          :stroke="hex"
          fill="none"
          :stroke-width="thickness"
          stroke-linecap="round"
        />
      </template>

      <!-- Straight line path -->
      <template v-else-if="straightLinePoints">
        <line
          :x1="straightLinePoints.x1"
          :y1="straightLinePoints.y1"
          :x2="straightLinePoints.x2"
          :y2="straightLinePoints.y2"
          :stroke="hex"
          fill="none"
          :stroke-width="thickness"
          stroke-linecap="round"
        />
      </template>

      <!-- Arrow heads -->
      <template v-if="pathData">
        <ArrowHead
          v-if="pathData.startHead !== 'none'"
          :position="pathData.start"
          :direction="pathData.startDir"
          :thickness="thickness"
          :arrow-thickness="baseThickness"
          :color="hex"
          :kind="pathData.startHead"
        />
        <ArrowHead
          v-if="pathData.endHead !== 'none'"
          :position="pathData.end"
          :direction="pathData.endDir"
          :thickness="thickness"
          :arrow-thickness="baseThickness"
          :color="hex"
          :kind="pathData.endHead"
        />

        <!-- Highlight overlay -->
        <template v-if="isEmphasized">
          <path
            v-if="isCurved && curvedPath"
            :d="curvedPath"
            class="highlight-overlay"
            fill="none"
            style="stroke-width: calc(2px / var(--ic-zoom))"
            stroke-linecap="round"
          />
          <line
            v-else-if="straightLinePoints"
            :x1="straightLinePoints.x1"
            :y1="straightLinePoints.y1"
            :x2="straightLinePoints.x2"
            :y2="straightLinePoints.y2"
            class="highlight-overlay"
            fill="none"
            style="stroke-width: calc(2px / var(--ic-zoom))"
            stroke-linecap="round"
          />
          <ArrowHead
            v-if="pathData.startHead !== 'none'"
            :position="pathData.start"
            :direction="pathData.startDir"
            thickness="calc(2px / var(--ic-zoom))"
            :arrow-thickness="baseThickness"
            color="var(--ic-highlighted-block-outline-color)"
            :kind="pathData.startHead"
          />
          <ArrowHead
            v-if="pathData.endHead !== 'none'"
            :position="pathData.end"
            :direction="pathData.endDir"
            thickness="calc(2px / var(--ic-zoom))"
            :arrow-thickness="baseThickness"
            color="var(--ic-highlighted-block-outline-color)"
            :kind="pathData.endHead"
          />
        </template>
      </template>
    </svg>
  </div>
</template>

<style scoped>
.ic-arc-arrow {
  display: flex;
  position: relative;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  overflow: visible;
  box-sizing: border-box;
}

.arrow-svg {
  width: 100%;
  height: 100%;
  overflow: visible !important;
}

.highlight-overlay {
  stroke: var(--ic-highlighted-block-outline-color);
}
</style>

<style>
.ic-block[data-hovered] > .ic-arc-arrow,
.ic-block[data-selected] > .ic-arc-arrow {
  outline: none;
}
</style>

// packages/extension-arrows/src/webComponents/ArcArrow.ts
import type { ICText, Snapshot } from '@infinitecanvas/core'
import { type Color, HitArc, type Text } from '@infinitecanvas/core/components'
import { ICEditableBlock } from '@infinitecanvas/core/elements'
import { type SVGTemplateResult, css, html, nothing, svg } from 'lit'
import { customElement, property, query } from 'lit/decorators.js'

import type { ArcArrow, ArrowTrim } from '../components'
import { ArrowHeadKind } from '../types'
import { ARROW_HEAD_GAP, getArrowHeadPath } from './common'

@customElement('ic-arc-arrow')
export class ICArcArrow extends ICEditableBlock {
  static styles = [
    ...super.styles,
    css`
    :host * {
      box-sizing: border-box;
      overflow: visible;
    }
    
    :host([is-hovered]) > :first-child::after,
    :host([is-selected]) > :first-child::after {
      border: none;
    }

    #container {
      display: flex;
      position: relative;
      align-items: center;
      justify-content: center;
      width: 100%;
      height: 100%;
      overflow: visible;
    }
    
    .arrow {
      width: 100%;
      height: 100%;
      overflow: visible !important;
    }
  `,
  ]

  @query('#container') container!: HTMLElement

  @query('ic-text') textElement!: ICText

  @property({ type: Object })
  public text!: Text

  @property({ type: Object })
  public color!: Color

  @property({ type: Object })
  public arcArrow!: ArcArrow

  @property({ type: Object })
  public arrowTrim: ArrowTrim | undefined = undefined

  private arc = new HitArc()

  public connectedCallback(): void {
    super.connectedCallback()

    const observer = new ResizeObserver(() => {
      this.requestUpdate()
    })
    observer.observe(this)
  }

  render() {
    const hex = this.color.toHex()

    if (this.arcArrow.isCurved()) {
      this.arc.update(
        [this.arcArrow.a[0] * this.clientWidth, this.arcArrow.a[1] * this.clientHeight],
        [this.arcArrow.b[0] * this.clientWidth, this.arcArrow.b[1] * this.clientHeight],
        [this.arcArrow.c[0] * this.clientWidth, this.arcArrow.c[1] * this.clientHeight],
      )
    }

    return html`
      <div id="container">
        <svg
          class="arrow"
          preserveAspectRatio="none"
        >
          ${this.isEmphasized ? this.getPath(2, 'var(--ic-gray-600)', '12', false) : null}
          ${this.getPath(this.arcArrow.thickness, hex, 'none', true)}
          ${this.isEmphasized ? this.getPath(2, 'var(--ic-highlighted-block-outline-color)', 'none', true) : null}
        </svg>
      </div>
    `
  }

  private getPath(thickness: number, color: string, dasharray: string, trim: boolean): SVGTemplateResult {
    if (this.arcArrow.isCurved()) {
      return this.getCurvedPath(thickness, color, dasharray, trim)
    }
    return this.getStraightPath(thickness, color, dasharray, trim)
  }

  private getCurvedPath(thickness: number, color: string, dasharray: string, trim: boolean): SVGTemplateResult {
    const arc = this.arc

    if (arc.length() === 0) {
      return svg``
    }

    let start = arc.a
    let end = arc.c
    let arcAngle = arc._arcAngle
    let tStart = 0
    let tEnd = 1
    if (trim && this.arrowTrim) {
      const gap = ARROW_HEAD_GAP / arc.length()

      tStart = this.arrowTrim.tStart
      if (tStart !== 0 && this.arcArrow.startArrowHead !== ArrowHeadKind.None) {
        tStart += gap
      }

      tEnd = this.arrowTrim.tEnd
      if (tEnd !== 1 && this.arcArrow.endArrowHead !== ArrowHeadKind.None) {
        tEnd -= gap
      }

      start = arc.parametricToPoint(tStart)
      end = arc.parametricToPoint(tEnd)
      arcAngle = arc._arcAngle * (tEnd - tStart)
    }

    const startDir = flipDirection(arc.directionAt(tStart))
    const endDir = arc.directionAt(tEnd)

    return svg`<path
      d="M ${start[0]} ${start[1]} A ${arc._radius} ${arc._radius} 0 ${arcAngle > Math.PI ? 1 : 0} ${arc._clockwise ? 0 : 1} ${end[0]} ${end[1]}"
      stroke="${color}"
      fill="none"
      stroke-width="${thickness}"
      stroke-dasharray="${dasharray}"
      stroke-linecap="round"
    />
    ${
      trim && this.arcArrow.startArrowHead !== ArrowHeadKind.None
        ? getArrowHeadPath(start, startDir, this.arcArrow.startArrowHead, thickness, color)
        : nothing
    }
    ${
      trim && this.arcArrow.endArrowHead !== ArrowHeadKind.None
        ? getArrowHeadPath(end, endDir, this.arcArrow.endArrowHead, thickness, color)
        : nothing
    }`
  }

  private getStraightPath(thickness: number, color: string, dasharray: string, trim: boolean): SVGTemplateResult {
    const a = [this.arcArrow.a[0] * this.clientWidth, this.arcArrow.a[1] * this.clientHeight]
    const c = [this.arcArrow.c[0] * this.clientWidth, this.arcArrow.c[1] * this.clientHeight]

    let start: [number, number] = [a[0], a[1]]
    let end: [number, number] = [c[0], c[1]]

    const vec: [number, number] = [end[0] - start[0], end[1] - start[1]]
    const length = Math.hypot(vec[0], vec[1])

    if (length === 0) {
      return svg``
    }

    let tStart = 0
    let tEnd = 1
    if (trim && this.arrowTrim) {
      const gap = ARROW_HEAD_GAP / length

      tStart = this.arrowTrim.tStart
      if (tStart !== 0 && this.arcArrow.startArrowHead !== ArrowHeadKind.None) {
        tStart += gap
      }

      tEnd = this.arrowTrim.tEnd
      if (tEnd !== 1 && this.arcArrow.endArrowHead !== ArrowHeadKind.None) {
        tEnd -= gap
      }

      start = [a[0] + (c[0] - a[0]) * tStart, a[1] + (c[1] - a[1]) * tStart]
      end = [a[0] + (c[0] - a[0]) * tEnd, a[1] + (c[1] - a[1]) * tEnd]
    }

    return svg`<line
      x1="${start[0]}"
      y1="${start[1]}"
      x2="${end[0]}"
      y2="${end[1]}"
      stroke="${color}"
      fill="none"
      stroke-width="${thickness}"
      stroke-linecap="round"
      stroke-dasharray="${dasharray}"
    />
    ${
      trim && this.arcArrow.startArrowHead !== ArrowHeadKind.None
        ? getArrowHeadPath(start, flipDirection(vec), this.arcArrow.startArrowHead, thickness, color)
        : nothing
    }
    ${
      trim && this.arcArrow.endArrowHead !== ArrowHeadKind.None
        ? getArrowHeadPath(end, vec, this.arcArrow.endArrowHead, thickness, color)
        : nothing
    }`
  }

  public getSnapshot(): Snapshot {
    // const snapshot = this.textElement.getSnapshot()

    // const { width, height, left, top } = this.computeBlockDimensions(this.container)

    // snapshot[this.blockId].Block.width = width
    // snapshot[this.blockId].Block.height = height
    // snapshot[this.blockId].Block.left = left
    // snapshot[this.blockId].Block.top = top

    // return snapshot

    return {}
  }
}

function flipDirection(direction: [number, number]): [number, number] {
  return [-direction[0], -direction[1]]
}

declare global {
  interface HTMLElementTagNameMap {
    'ic-arc-arrow': ICArcArrow
  }
}
