// packages/extension-sticky-notes/src/webComponents/StickyNote.ts
import { type ICText, type Snapshot, TextAlign, VerticalAlign } from '@infinitecanvas/core'
import type { Color, Text, VerticalAlign as VerticalAlignComp } from '@infinitecanvas/core/components'
import { ICEditableBlock } from '@infinitecanvas/core/elements'

import { css, html } from 'lit'
import { customElement, property, query } from 'lit/decorators.js'
import { styleMap } from 'lit/directives/style-map.js'

@customElement('ic-sticky-note')
export class ICStickyNote extends ICEditableBlock {
  @query('#container') container!: HTMLElement
  @query('ic-text') textElement!: ICText

  @property({ type: Object })
  public text!: Text

  @property({ type: Object })
  public color!: Color

  @property({ type: Object })
  public verticalAlign!: VerticalAlignComp

  static styles = [
    ...super.styles,
    css`
      #container {
        width: 100%;
        display: flex;
        padding: 8%;
        aspect-ratio: 1 / 1;
        box-sizing: border-box;
        box-shadow:
          rgba(16, 24, 32, 0.65) 0px 4px 5px -6px,
          rgba(16, 24, 32, 0.45) 0px 11px 13px -12px,
          rgba(16, 24, 45, 0.025) 0px 45px 10px -12px inset;
      }
  `,
  ]

  render() {
    const alignStyle =
      {
        [VerticalAlign.Top]: 'flex-start',
        [VerticalAlign.Center]: 'center',
        [VerticalAlign.Bottom]: 'flex-end',
      }[this.verticalAlign.value] || 'flex-start'

    return html`
      <div id="container" style=${styleMap({
        'background-color': `rgb(${this.color.red}, ${this.color.green}, ${this.color.blue})`,
        'align-items': alignStyle,
      })}>
        <ic-text 
          blockId=${this.blockId}
          .isEditing=${this.isEditing}
          .text=${this.text}
          .defaultAlignment=${TextAlign.Center}
        ></ic-text>
    </div>
    `
  }

  public getSnapshot(): Snapshot {
    const snapshot = this.textElement.getSnapshot()

    const { width, height, left, top } = this.computeBlockDimensions(this.container)

    snapshot[this.blockId].Block.width = width
    snapshot[this.blockId].Block.height = height
    snapshot[this.blockId].Block.left = left
    snapshot[this.blockId].Block.top = top

    return snapshot
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ic-sticky-note': ICStickyNote
  }
}

// packages/vue/src/components/blocks/StickyNote.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useComponent } from "../../composables/useComponent";
import { useTextStretchBehavior } from "../../composables/useTextStretchBehavior";
import {
  Color,
  VerticalAlign,
  VerticalAlignment,
} from "@infinitecanvas/core";
import type { BlockData } from "../../types";
import EditableText from "../EditableText.vue";

const props = defineProps<BlockData>();

const color = useComponent(props.entityId, Color);
const verticalAlign = useComponent(props.entityId, VerticalAlign);

const containerRef = ref<HTMLElement | null>(null);

const alignItemsMap: Record<string, string> = {
  [VerticalAlignment.Top]: "flex-start",
  [VerticalAlignment.Center]: "center",
  [VerticalAlignment.Bottom]: "flex-end",
};

const containerStyle = computed(() => ({
  backgroundColor: color.value
    ? `rgb(${color.value.red}, ${color.value.green}, ${color.value.blue})`
    : undefined,
  // Min-height = block width to maintain square minimum
  minHeight: `${props.block.size[0]}px`,
  alignItems:
    alignItemsMap[verticalAlign.value?.value ?? VerticalAlignment.Top],
}));

// Use composable for text stretch behavior with square minimum height
const { handleEditEnd } = useTextStretchBehavior({
  blockData: props,
  containerRef,
  minWidth: () => props.block.size[0],
  minHeight: () => props.block.size[0],
});
</script>

<template>
  <div ref="containerRef" class="ic-sticky-note" :style="containerStyle">
    <EditableText
      v-bind="props"
      :block-element="containerRef"
      @edit-end="handleEditEnd"
    />
  </div>
</template>

<style>
.ic-sticky-note {
  width: 100%;
  height: fit-content;
  display: flex;
  padding: 8%;
  box-sizing: border-box;
  box-shadow:
    rgba(16, 24, 32, 0.65) 0px 4px 5px -6px,
    rgba(16, 24, 32, 0.45) 0px 11px 13px -12px,
    rgba(16, 24, 45, 0.025) 0px 45px 10px -12px inset;
}
</style>
