// packages/vue/src/components/blocks/SelectionBox.vue
<script setup lang="ts">
/**
 * Default SelectionBox component - the marquee selection rectangle.
 * Rendered while dragging on empty canvas space to select multiple blocks.
 *
 * Uses CSS variables:
 * --ic-zoom: Current zoom level (for scaling border width)
 * --ic-primary: Primary color for the border
 */
</script>

<template>
  <div class="ic-selection-box" />
</template>

<style>
.ic-selection-box {
  box-sizing: border-box;
  width: 100%;
  height: 100%;
  background-color: var(--ic-selection-box-bg);
  border-style: solid;
  border-width: calc(3px / var(--ic-zoom));
  border-color: var(--ic-primary);
}
</style>

// packages/extension-transform/src/webComponents/selectionBox.ts
import { ICBaseMenuButton } from '@infinitecanvas/core/elements'
import { css, html } from 'lit'
import { customElement } from 'lit/decorators.js'

@customElement('ic-selection-box')
export class SelectionBoxElement extends ICBaseMenuButton {
  static styles = css`
    div {
      box-sizing: border-box;
      width: 100%;
      height: 100%;
      background-color: #5865f222;
      border-style: solid;
      border-width: calc(3px / var(--ic-zoom));
      border-color: var(--ic-primary);
    }
  `

  render() {
    return html`
      <div></div>
    `
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ic-selection-box': SelectionBoxElement
  }
}
